services:
  app:
    build: .
    container_name: vidi-ledger-app
    ports:
      - "3018:3018"
    environment:
      - DB_TYPE=${DB_TYPE:-postgres}
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
    restart: always
